### ISSUE TITLE
Automatically mark todo as done when matching iOS reminder is completed

### ISSUE THREAD

**Issue by tgdnt** [tgdnt/remind#1]
Implement a command such as `todo.sh remind fetch` that will read your completed iOS reminders
and mark their matching todos as done.

**Comment by tgdnt** [comment]
I am working on this area under branch `roundtrip`.

- [x] Add reminderID to todo item e004a6ff294b0f19c8114387d7f4c15f71cac6ee
- [x] Delete corresponding reminder when todo is done 862424e
- [ ] Automatically round trip: find all todos with reminders, check corresponding reminder for completion, if completed, complete the todo and delete the reminder.
